### ISSUE TITLE
remoteMode=true no longer exists

### ISSUE THREAD

**Issue by mikerocklewitz** [mainsail-crew/docs#28]
### Mainsail Version:

Current

### Browser:

Other (Please tell us below)

### Device:

Other (Please tell us below)

### Operating System:

Other (Please tell us below)

### What happened?

In the most recent versions of mainsail, running in docker I'm no longer able to specify printer ip address with the remoteMode=true in config.json   Using docker on unraid server.

### What did you expect to happen instead?

I expected to get the add printer dialogue but consistently got cannot connect to moonraker.

### How to reproduce this bug?

Set things up according to docker documentation using remoteMode in config.json

### Additional information:

I found the solution to the problem.  Instead of using remoteMode=true, as listed in documentation replace with

{
  "instancesDB": "browser"
}

**Comment by th33xitus** [comment]
Hi, thanks for the headsup. I transferred the issue to this repo as it has to be solved in here.

The page you are referring to is probably this one:
<https://docs.mainsail.xyz/setup/docker#configuration-for-the-docker-image>

You are right, we need to correct that part.
