### ISSUE TITLE
Please add theme "blurry" to community themes

### ISSUE THREAD

**Issue by bumbeng** [mainsail-crew/docs#39]
##  https://github.com/bumbeng/mainsail_theme_blurry

![Screenshot](https://github.com/mainsail-crew/docs/assets/111509593/fc00958d-c080-4a46-a845-3a2cfda6bf54)

**Comment by meteyou** [comment]
please create a PR in this repo: https://github.com/mainsail-crew/gb-docs and add your theme to this file: https://github.com/mainsail-crew/gb-docs/blob/main/_data/themes.csv

this repo is the old docs repo.
