### ISSUE TITLE
Please add theme "clean" to community themes

### ISSUE THREAD

**Issue by bumbeng** [mainsail-crew/docs#40]
## https://github.com/bumbeng/mainsail_theme_clean

![Screenshot](https://github.com/mainsail-crew/docs/assets/111509593/172e9860-cb39-4b17-9f2d-9e0e077b9650)

**Comment by meteyou** [comment]
please create a PR in this repo: https://github.com/mainsail-crew/gb-docs and add your theme to this file: https://github.com/mainsail-crew/gb-docs/blob/main/_data/themes.csv

this repo is the old docs repo.
