### ISSUE TITLE
adapt to change in label objects option in PrusaSlicer

### ISSUE THREAD

**Issue by tweh** [mainsail-crew/docs#41]
With the new version [2.7.0 of Prusa Slicer](https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.7.0-alpha1) it changed it’s option `Label Objects` to become a drop down and thus the screenshot in the [mainsail docs ](https://docs.mainsail.xyz/overview/features/exclude-objects). So at the moment the docs show only a check box, where as far as I understand one must 1. select *Firmware-specific* and 2. in the Print settings and *Klipper* as g-Code flavor in the printer settings.

The docs should look like this:

----

In PrusaSlicer or SuperSlicer you have to chose *Firmware-specific* in:

    Print Settings > Output options > Output file > Label objects

![Bildschirmfoto 2023-11-25 um 15 57 41](https://github.com/mainsail-crew/mainsail/assets/3011538/0973b74c-65cb-470c-84c8-dd5ee04ae22f)

And you maust ensure that in the printer settings you choose *Klipper* as G-code flavor. You’ll find this in:

    Printer Settings > General > Firmware > G-code flavor

![Bildschirmfoto 2023-11-25 um 15 57 49](https://github.com/mainsail-crew/mainsail/assets/3011538/8aa07043-a936-41df-aee4-30e7b4bf0d6f)

**Comment by meteyou** [comment]
this is also our old repo for the docs. it doesnt matter. i updated the docs. thank you very much!

**Comment by tweh** [comment]
Thanks!
